/* 
 * Copyright (c) 1998-2003 Massachusetts Institute of Technology. 
 * This code was developed as part of the Haystack research project 
 * (http://haystack.lcs.mit.edu/). Permission is hereby granted, 
 * free of charge, to any person obtaining a copy of this software 
 * and associated documentation files (the "Software"), to deal in 
 * the Software without restriction, including without limitation 
 * the rights to use, copy, modify, merge, publish, distribute, 
 * sublicense, and/or sell copies of the Software, and to permit 
 * persons to whom the Software is furnished to do so, subject to 
 * the following conditions: 
 * 
 * The above copyright notice and this permission notice shall be 
 * included in all copies or substantial portions of the Software. 
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES 
 * OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, 
 * WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR 
 * OTHER DEALINGS IN THE SOFTWARE. 
 */

/* DO NOT EDIT THIS FILE - it is machine generated */

#include "jni_md.h"

#include <jni.h>

/* Header for class edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService */

#ifndef _Included_edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
#define _Included_edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
 * Method:    add
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jint JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_add
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

// the last argument is an array of authors
JNIEXPORT jboolean JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_addAuthored
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray);

JNIEXPORT jobjectArray JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_getAuthors
  (JNIEnv *, jobject, jobject);

JNIEXPORT jobjectArray JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_getAuthoredStatementIDs
  (JNIEnv *, jobject, jobject);



/*
 * Class:     edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
 * Method:    remove
 * Signature: (Ljava/lang/String;Ledu/mit/lcs/haystack/rdf/Statement;[Ledu/mit/lcs/haystack/rdf/Resource;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_remove
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
 * Method:    query
 * Signature: (Ljava/lang/String;[Ledu/mit/lcs/haystack/rdf/Statement;[Ledu/mit/lcs/haystack/rdf/Resource;[Ledu/mit/lcs/haystack/rdf/Resource;)Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_query
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray);

JNIEXPORT jobject JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_queryMulti
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray);


/*
 * Class:     edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
 * Method:    contains
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_contains
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
 * Method:    extract
 * Signature: (Ljava/lang/String;Ledu/mit/lcs/haystack/rdf/Resource;Ledu/mit/lcs/haystack/rdf/Resource;Ledu/mit/lcs/haystack/rdf/RDFNode;)Ledu/mit/lcs/haystack/rdf/RDFNode;
 */
JNIEXPORT jobject JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_extract
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
 * Method:    getStatement
 * Signature: (Ljava/lang/String;Ledu/mit/lcs/haystack/rdf/Resource;)Ledu/mit/lcs/haystack/rdf/Statement;
 */
JNIEXPORT jobject JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_getStatement
  (JNIEnv *, jobject, jobject);

/*
 * Class:     edu_mit_lcs_haystack_server_rdfstore_CholesterolRDFStoreService
 * Method:    doNativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_doNativeInit
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_doNativeKill
  (JNIEnv * env, jobject obj);

JNIEXPORT void JNICALL Java_edu_mit_lcs_haystack_server_rdfstore_Cholesterol3RDFStoreService_setDefrag
  (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
